# Generated by Django 5.0.2 on 2024-03-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, default='null'),
            preserve_default=False,
        ),
    ]
